### ISSUE TITLE
Unable To add and edit Hotel

### ISSUE THREAD

**Issue by Harsh5674** [chrisblakely01/mern-booking-app#9]
When I try to add hotel ,I get these errors below:

![issue 2](https://github.com/chrisblakely01/mern-booking-app/assets/135805103/c38e52dc-15f3-42b4-9a93-c3d177570586)
![issue 4](https://github.com/chrisblakely01/mern-booking-app/assets/135805103/ea98d540-c325-49f3-bc85-4a9d2ee13ca9)
I can see that images are successfully uploaded to cloudinary but still unable to add hotel.

when I try to edit hotel ,I am able to successfully change other parameters but not able to add images (Error saving hotel)
![issue 3](https://github.com/chrisblakely01/mern-booking-app/assets/135805103/7a791235-d644-4132-b5ed-ff2fed00b8cd)

**Comment by FullerWeb** [comment]
@Harsh5674 Have you been able to get a resolution for your issue? I am experiencing the same issue.

**Comment by FullerWeb** [comment]
I have isolated the problem but not sure how to fix it at this moment. The server is receiving the auth cookie, however, it is not decrypting it properly. I ran a console.log(req.userId) and it is coming up 'undefined' which is why the hotel is not being saved.

**Comment by FullerWeb** [comment]
I discovered the issue. In middleware/auth.ts, the token was referencing the wrong object property. A JWTPayload type does not have a prop key of (decoded as JwtPayload).userId. This is what was configured. After changing the line to req.userId = (decoded as JwtPayload).userID; the test successfully passed.

**Comment by Harsh5674** [comment]
Thanks , i have succesfuly resolved it.
